name: lab6

services:
  backend:
    image: tomcat_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - my_net
    restart: always

  database:
    image: mysql:9.1.0
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql_data
    networks:
      - my_net

volumes:
  mysql_data:
    external: true

networks:
  my_net:
    driver: bridge